export const WORDS_BY_CATEGORY = {
  genel: [
    { word: "JavaScript", taboo: ["Programlama", "React", "Web", "Kod", "Değişken"] },
    { word: "Gitar", taboo: ["Müzik", "Tel", "Pena", "Akustik", "Elektro"] },
    { word: "Kahve", taboo: ["Fincan", "Sıcak", "İçecek", "Kafein", "Çekirdek"] },
    { word: "Kitap", taboo: ["Okumak", "Sayfa", "Yazar", "Roman", "Kütüphane"] },
    { word: "Araba", taboo: ["Tekerlek", "Motor", "Sürmek", "Yol", "Direksiyon"] },
    { word: "Saat", taboo: ["Zaman", "Akrep", "Yelkovan", "Kol", "Dijital"] },
    { word: "Gözlük", taboo: ["Cam", "Çerçeve", "Bakmak", "Miyop", "Güneş"] },
    { word: "Para", taboo: ["Nakit", "Bozuk", "Cüzdan", "Banka", "Zengin"] },
    { word: "Ev", taboo: ["Oda", "Kapı", "Pencere", "Aile", "Yaşamak"] },
    { word: "Okul", taboo: ["Öğrenci", "Öğretmen", "Ders", "Sınıf", "Sınav"] },
    { word: "Aile", taboo: ["Anne", "Baba", "Kardeş", "Akraba", "Ev"] },
    { word: "Arkadaş", taboo: ["Dost", "Sırdaş", "Sohbet", "Güven", "Samimi"] },
    { word: "Deniz", taboo: ["Su", "Dalga", "Plaj", "Yüzmek", "Gemi"] },
    { word: "Güneş", taboo: ["Sıcak", "Yaz", "Işık", "Gökyüzü", "Sarı"] },
    { word: "Ay", taboo: ["Gece", "Yıldız", "Dolunay", "Uydu", "Gümüş"] },
    { word: "Yıldız", taboo: ["Gökyüzü", "Parlak", "Gece", "Kaymak", "Samanyolu"] },
    { word: "Yağmur", taboo: ["Islanmak", "Şemsiye", "Bulut", "Su", "Fırtına"] },
    { word: "Kar", taboo: ["Soğuk", "Kış", "Beyaz", "Adam", "Lapa"] },
    { word: "Rüzgar", taboo: ["Esmek", "Fırtına", "Serin", "Uçurtma", "Yel"] },
    { word: "Ağaç", taboo: ["Yaprak", "Orman", "Dal", "Kök", "Yeşil"] },
    { word: "Çiçek", taboo: ["Koku", "Yaprak", "Bahçe", "Gül", "Vazo"] },
    { word: "Kedi", taboo: ["Miyav", "Bıyık", "Tüy", "Hayvan", "Fare"] },
    { word: "Köpek", taboo: ["Havlamak", "Sadık", "Tasma", "Kemik", "Hayvan"] },
    { word: "Kuş", taboo: ["Uçmak", "Kanat", "Gaga", "Yuva", "Tüy"] },
    { word: "Balık", taboo: ["Yüzmek", "Deniz", "Akvaryum", "Olta", "Solungaç"] },
  ],
  spor: [
    { word: "Futbol", taboo: ["Top", "Kale", "Takım", "Gol", "Maç"] },
    { word: "Basketbol", taboo: ["Pota", "Smaç", "Top", "Saha", "LeBron James"] },
    { word: "Voleybol", taboo: ["File", "Smaç", "Manşet", "Servis", "Takım"] },
    { word: "Tenis", taboo: ["Raket", "Top", "Kort", "Wimbledon", "Federer"] },
    { word: "Yüzme", taboo: ["Havuz", "Su", "Kulaç", "Serbest", "Kelebek"] },
    { word: "Atletizm", taboo: ["Koşu", "Pist", "Maraton", "Rekor", "Olimpiyat"] },
    { word: "Boks", taboo: ["Ring", "Eldiven", "Yumruk", "Nakavt", "Muhammed Ali"] },
    { word: "Güreş", taboo: ["Minder", "Pehlivan", "Tuş", "Kündeye getirmek", "Yağlı"] },
    { word: "Halter", taboo: ["Ağırlık", "Kaldırmak", "Bar", "Naim Süleymanoğlu", "Koparma"] },
    { word: "Kayak", taboo: ["Kar", "Dağ", "Baton", "Pist", "Kış"] },
    { word: "Jimnastik", taboo: ["Esneklik", "Artistik", "Minder", "Barfiks", "Halka"] },
    { word: "Hentbol", taboo: ["Kale", "Top", "Gol", "Saha", "Yedi metre"] },
    { word: "Golf", taboo: ["Sopa", "Top", "Delik", "Çim", "Tiger Woods"] },
    { word: "Formula 1", taboo: ["Araba", "Yarış", "Pist", "Pilot", "Schumacher"] },
    { word: "Bisiklet", taboo: ["Pedal", "Tekerlek", "Sürmek", "Yarış", "Tur"] },
    { word: "Maraton", taboo: ["Koşu", "Uzun mesafe", "Atletizm", "42 km", "Bitiş"] },
    { word: "Raket", taboo: ["Tenis", "Badminton", "Top", "Vurmak", "File"] },
    { word: "Antrenman", taboo: ["Spor", "Egzersiz", "Çalışmak", "Koç", "Hazırlık"] },
    { word: "Hakem", taboo: ["Maç", "Düdük", "Kart", "Kural", "Karar"] },
    { word: "Olimpiyat", taboo: ["Madalya", "Spor", "Meşale", "Yarışma", "Dört yıl"] },
    { word: "Madalya", taboo: ["Altın", "Gümüş", "Bronz", "Kazanmak", "Ödül"] },
    { word: "Rekor", taboo: ["Kırmak", "En iyi", "Derece", "Guinness", "Atletizm"] },
    { word: "Stadyum", taboo: ["Taraftar", "Maç", "Tribün", "Saha", "Atmosfer"] },
    { word: "Krampon", taboo: ["Futbol", "Ayakkabı", "Çivili", "Saha", "Top"] },
    { word: "Pota", taboo: ["Basketbol", "Smaç", "Sayı", "Çember", "File"] },
  ],
  film: [
    { word: "Yüzüklerin Efendisi", taboo: ["Frodo", "Gandalf", "Ork", "Tek Yüzük", "Orta Dünya"] },
    { word: "Titanik", taboo: ["Gemi", "Buzdağı", "Jack", "Rose", "Leonardo DiCaprio"] },
    { word: "Harry Potter", taboo: ["Büyücü", "Asa", "Hogwarts", "Voldemort", "Gözlük"] },
    { word: "Star Wars", taboo: ["Yıldız Savaşları", "Jedi", "Darth Vader", "Işın Kılıcı", "Uzay"] },
    { word: "Matrix", taboo: ["Neo", "Morpheus", "Ajan Smith", "Sanal Gerçeklik", "Kırmızı Hap"] },
    { word: "Baba", taboo: ["Godfather", "Mafya", "Marlon Brando", "Corleone", "İtalya"] },
    { word: "Esaretin Bedeli", taboo: ["Hapishane", "Andy Dufresne", "Morgan Freeman", "Umut", "Kaçış"] },
    { word: "Kara Şövalye", taboo: ["Batman", "Joker", "Heath Ledger", "Gotham", "Yarasa"] },
    { word: "Forrest Gump", taboo: ["Tom Hanks", "Koşmak", "Jenny", "Çikolata", "Hayat"] },
    { word: "Ucuz Roman", taboo: ["Pulp Fiction", "Tarantino", "Dans", "Çanta", "John Travolta"] },
    { word: "Başlangıç", taboo: ["Inception", "Rüya", "Leonardo DiCaprio", "Topaç", "Katman"] },
    { word: "Dövüş Kulübü", taboo: ["Fight Club", "Brad Pitt", "Sabun", "Tyler Durden", "Yıkım"] },
    { word: "Avatar", taboo: ["Pandora", "Na'vi", "Mavi", "James Cameron", "3D"] },
    { word: "Jurassic Park", taboo: ["Dinozor", "Ada", "T-Rex", "DNA", "Spielberg"] },
    { word: "Yönetmen", taboo: ["Film", "Çekmek", "Kamera", "Sahne", "Tarantino"] },
    { word: "Senaryo", taboo: ["Yazar", "Hikaye", "Diyalog", "Film", "Metin"] },
    { word: "Oyuncu", taboo: ["Aktör", "Aktris", "Rol", "Karakter", "Sahne"] },
    { word: "Kamera", taboo: ["Çekim", "Lens", "Film", "Yönetmen", "Tripod"] },
    { word: "Sinema", taboo: ["Film", "Salon", "Perde", "Mısır", "Bilet"] },
    { word: "Oscar", taboo: ["Ödül", "Akademi", "Heykelcik", "Tören", "En İyi Film"] },
    { word: "Gişe", taboo: ["Hasılat", "Para", "Bilet", "Sinema", "Popüler"] },
    { word: "Fragman", taboo: ["Tanıtım", "Film", "Video", "Reklam", "İzlemek"] },
    { word: "Patlamış Mısır", taboo: ["Sinema", "Tuzlu", "Atıştırmalık", "Kova", "Sarı"] },
    { word: "Bilet", taboo: ["Sinema", "Konser", "Giriş", "Koltuk", "Fiyat"] },
    { word: "Sahne", taboo: ["Film", "Tiyatro", "Perde", "Dekor", "Çekim"] },
  ],
  yemek: [
    { word: "Makarna", taboo: ["Sos", "Spagetti", "İtalyan", "Peynir", "Domates"] },
    { word: "Pizza", taboo: ["Hamur", "Fırın", "Dilim", "Margarita", "Sucuk"] },
    { word: "Kebap", taboo: ["Et", "Şiş", "Mangal", "Adana", "Urfa"] },
    { word: "Döner", taboo: ["Et", "Tavuk", "Ekmek Arası", "Lavaş", "İskender"] },
    { word: "Lahmacun", taboo: ["Hamur", "Kıyma", "Fırın", "Acılı", "Limon"] },
    { word: "Mantı", taboo: ["Hamur", "Kıyma", "Yoğurt", "Sarımsak", "Kayseri"] },
    { word: "Baklava", taboo: ["Tatlı", "Şerbet", "Fıstık", "Ceviz", "Hamur"] },
    { word: "Çorba", taboo: ["Sıcak", "Kaşık", "Mercimek", "Kase", "İçmek"] },
    { word: "Salata", taboo: ["Yeşillik", "Domates", "Salatalık", "Sos", "Marul"] },
    { word: "Pilav", taboo: ["Pirinç", "Tane", "Tereyağı", "Nohut", "Tencere"] },
    { word: "Balık", taboo: ["Deniz", "Izgara", "Kılçık", "Levrek", "Hamsi"] },
    { word: "Tavuk", taboo: ["Kanat", "But", "Göğüs", "Izgara", "Beyaz Et"] },
    { word: "Hamburger", taboo: ["Ekmek", "Köfte", "Patates", "Fast Food", "Marul"] },
    { word: "Patates Kızartması", taboo: ["Yağ", "Tuz", "Ketçap", "Mayonez", "Çıtır"] },
    { word: "Dondurma", taboo: ["Soğuk", "Yaz", "Külah", "Süt", "Top"] },
    { word: "Peynir", taboo: ["Süt", "Beyaz", "Kaşar", "Kahvaltı", "Ezine"] },
    { word: "Zeytin", taboo: ["Siyah", "Yeşil", "Kahvaltı", "Ağaç", "Yağ"] },
    { word: "Ekmek", taboo: ["Un", "Hamur", "Fırın", "Dilim", "Buğday"] },
    { word: "Restoran", taboo: ["Yemek", "Garson", "Masa", "Menü", "Hesap"] },
    { word: "Şef", taboo: ["Aşçı", "Mutfak", "Yemek", "Bıçak", "Önlük"] },
    { word: "Mutfak", taboo: ["Yemek", "Pişirmek", "Ocak", "Tencere", "Buzdolabı"] },
    { word: "Tarif", taboo: ["Yemek", "Malzeme", "Ölçü", "Pişirmek", "Kitap"] },
    { word: "Tatlı", taboo: ["Şeker", "Çikolata", "Pasta", "Baklava", "Sütlaç"] },
    { word: "Acı", taboo: ["Biber", "Tat", "Sos", "Sıcak", "Yakmak"] },
    { word: "Tuz", taboo: ["Tat", "Beyaz", "Deniz", "Yemek", "Kristal"] },
  ],
  teknoloji: [
    { word: "Bilgisayar", taboo: ["Monitör", "Klavye", "Fare", "İşlemci", "Yazılım"] },
    { word: "Akıllı Telefon", taboo: ["Ekran", "Uygulama", "Arama", "Mesaj", "Android"] },
    { word: "İnternet", taboo: ["Web", "Site", "Tarayıcı", "Bağlantı", "Wifi"] },
    { word: "Yapay Zeka", taboo: ["Robot", "Makine Öğrenmesi", "Akıllı", "Algoritma", "ChatGPT"] },
    { word: "Robot", taboo: ["Makine", "Otomasyon", "Yapay Zeka", "Metal", "İnsan"] },
    { word: "Yazılım", taboo: ["Kod", "Program", "Bilgisayar", "Uygulama", "Geliştirici"] },
    { word: "Donanım", taboo: ["Hardware", "Bilgisayar", "Parça", "İşlemci", "Ekran Kartı"] },
    { word: "Klavye", taboo: ["Tuş", "Yazmak", "Harf", "Bilgisayar", "Mekanik"] },
    { word: "Fare", taboo: ["Mouse", "Tıklamak", "İmleç", "Bilgisayar", "Tekerlek"] },
    { word: "Monitör", taboo: ["Ekran", "Görüntü", "Bilgisayar", "Piksel", "LED"] },
    { word: "Dizüstü Bilgisayar", taboo: ["Laptop", "Taşınabilir", "Batarya", "Ekran", "Klavye"] },
    { word: "Tablet", taboo: ["Dokunmatik", "Ekran", "iPad", "Android", "Mobil"] },
    { word: "Sosyal Medya", taboo: ["Facebook", "Twitter", "Instagram", "Paylaşmak", "Profil"] },
    { word: "E-posta", taboo: ["Mail", "Mesaj", "Göndermek", "Adres", "Gelen Kutusu"] },
    { word: "Uygulama", taboo: ["App", "Telefon", "İndirmek", "Store", "Mobil"] },
    { word: "Kodlama", taboo: ["Yazılım", "Programlama", "Dil", "Geliştirici", "Satır"] },
    { word: "Veritabanı", taboo: ["Database", "SQL", "Tablo", "Veri", "Sorgu"] },
    { word: "Sunucu", taboo: ["Server", "Bilgisayar", "Ağ", "Hosting", "Veri Merkezi"] },
    { word: "Bulut", taboo: ["Cloud", "Depolama", "İnternet", "Sunucu", "Veri"] },
    { word: "Drone", taboo: ["Uçmak", "Kamera", "Pervane", "İnsansız", "Hava Aracı"] },
    { word: "Sanal Gerçeklik", taboo: ["VR", "Gözlük", "Oyun", "Simülasyon", "3D"] },
    { word: "Artırılmış Gerçeklik", taboo: ["AR", "Kamera", "Telefon", "Görüntü", "Sanal"] },
    { word: "Şifre", taboo: ["Password", "Güvenlik", "Giriş", "Karakter", "Gizli"] },
    { word: "Algoritma", taboo: ["Kod", "Mantık", "Sıra", "Problem", "Çözüm"] },
    { word: "Piksel", taboo: ["Ekran", "Görüntü", "Nokta", "Çözünürlük", "Monitör"] },
  ],
  tarih: [
    { word: "Osmanlı", taboo: ["İmparatorluk", "Padişah", "Saray", "Tuğra", "600 yıl"] },
    { word: "Fatih Sultan Mehmet", taboo: ["İstanbul", "Fetih", "1453", "Padişah", "Top"] },
    { word: "Atatürk", taboo: ["Cumhuriyet", "Anıtkabir", "Lider", "Türkiye", "Samsun"] },
    { word: "Piramit", taboo: ["Mısır", "Firavun", "Mezar", "Antik", "Gize"] },
    { word: "Gladyatör", taboo: ["Roma", "Kolezyum", "Dövüş", "Arena", "Köle"] },
    { word: "Viking", taboo: ["Gemi", "Savaşçı", "Kuzey", "İskandinavya", "Balta"] },
    { word: "Orta Çağ", taboo: ["Şövalye", "Kale", "Kral", "Derebeylik", "Veba"] },
    { word: "Rönesans", taboo: ["Sanat", "Yeniden Doğuş", "İtalya", "Da Vinci", "Tablo"] },
    { word: "Sanayi Devrimi", taboo: ["Makine", "Fabrika", "Buhar", "İngiltere", "Üretim"] },
    { word: "Kurtuluş Savaşı", taboo: ["İstiklal", "Milli Mücadele", "Atatürk", "İnönü", "Cephe"] },
    { word: "Yazı", taboo: ["Sümerler", "Çivi", "Kil Tablet", "Harf", "Alfabe"] },
    { word: "Tekerlek", taboo: ["İcat", "Mezopotamya", "Dönmek", "Araba", "Ulaşım"] },
    { word: "Barut", taboo: ["Çin", "Patlama", "Silah", "Top", "Ateş"] },
    { word: "Matbaa", taboo: ["Gutenberg", "Kitap", "Baskı", "Kağıt", "Yayın"] },
    { word: "Berlin Duvarı", taboo: ["Almanya", "Soğuk Savaş", "Yıkılmak", "Doğu", "Batı"] },
    { word: "İpek Yolu", taboo: ["Ticaret", "Kervan", "Çin", "Baharat", "Marco Polo"] },
    { word: "Haçlı Seferleri", taboo: ["Kudüs", "Hristiyan", "Müslüman", "Savaş", "Papa"] },
    { word: "Fransız İhtilali", taboo: ["Bastille", "1789", "Liberté", "Giyotin", "Napolyon"] },
    { word: "Soğuk Savaş", taboo: ["ABD", "Sovyetler Birliği", "Nükleer", "Casus", "Uzay Yarışı"] },
    { word: "Reform", taboo: ["Martin Luther", "Kilise", "Protestan", "İncil", "Almanya"] },
    { word: "Savaş", taboo: ["Ordu", "Asker", "Silah", "Barış", "Cephe"] },
    { word: "Barış", taboo: ["Savaş", "Anlaşma", "Güvercin", "Ateşkes", "Nobel"] },
    { word: "Arkeolog", taboo: ["Kazı", "Tarih", "Eski Eser", "Müze", "Harabe"] },
    { word: "İmparator", taboo: ["Roma", "Kral", "Sezar", "Taç", "Yönetici"] },
    { word: "Kraliçe", taboo: ["İngiltere", "Elizabeth", "Taç", "Saray", "Monarşi"] },
  ],
  coğrafya: [
    { word: "Ekvator", taboo: ["Çizgi", "Dünya", "Sıcak", "Orta", "Hayali"] },
    { word: "Kutup", taboo: ["Soğuk", "Buz", "Ayı", "Kuzey", "Güney"] },
    { word: "Volkan", taboo: ["Dağ", "Patlama", "Lav", "Magma", "Yanardağ"] },
    { word: "Deprem", taboo: ["Sallanmak", "Fay Hattı", "Richter", "Tektonik", "Afet"] },
    { word: "Okyanus", taboo: ["Deniz", "Büyük", "Atlas", "Pasifik", "Su"] },
    { word: "Kıta", taboo: ["Asya", "Avrupa", "Afrika", "Kara Parçası", "Amerika"] },
    { word: "Ada", taboo: ["Deniz", "Kara", "Etrafı Su", "Yalnız", "Robinson Crusoe"] },
    { word: "Çöl", taboo: ["Sıcak", "Kum", "Deve", "Vaha", "Sahra"] },
    { word: "Orman", taboo: ["Ağaç", "Yeşil", "Vahşi Yaşam", "Amazon", "Balta"] },
    { word: "Nehir", taboo: ["Irmak", "Su", "Akarsu", "Nil", "Yatak"] },
    { word: "Göl", taboo: ["Su", "Van", "Tatlı", "Durgun", "Kenar"] },
    { word: "Dağ", taboo: ["Zirve", "Yüksek", "Tırmanmak", "Everest", "Ağrı"] },
    { word: "Harita", taboo: ["Coğrafya", "Atlas", "Yön", "Pusula", "Ölçek"] },
    { word: "Pusula", taboo: ["Yön", "Kuzey", "Manyetik", "İbre", "Harita"] },
    { word: "İklim", taboo: ["Hava", "Mevsim", "Sıcaklık", "Yağış", "Muson"] },
    { word: "Muson", taboo: ["Yağmur", "Yaz", "Hindistan", "Asya", "İklim"] },
    { word: "Tsunami", taboo: ["Deprem", "Dalga", "Okyanus", "Dev", "Japonya"] },
    { word: "Şelale", taboo: ["Su", "Akarsu", "Düşmek", "Yüksek", "Niagara"] },
    { word: "Plato", taboo: ["Yayla", "Düzlük", "Yüksek", "Coğrafya", "Arazi"] },
    { word: "Vadi", taboo: ["Dağ", "Nehir", "Aralık", "Yeşil", "Manzara"] },
    { word: "Körfez", taboo: ["Deniz", "Girinti", "İzmit", "Basra", "Liman"] },
    { word: "Boğaz", taboo: ["İstanbul", "Deniz", "Geçit", "Köprü", "Çanakkale"] },
    { word: "Başkent", taboo: ["Ülke", "Ankara", "Yönetim", "Merkez", "Şehir"] },
    { word: "Nüfus", taboo: ["İnsan", "Sayı", "Kalabalık", "Yoğunluk", "Sayım"] },
    { word: "Sınır", taboo: ["Ülke", "Komşu", "Çizgi", "Kapı", "Geçmek"] },
  ],
  bilim: [
    { word: "DNA", taboo: ["Genetik", "Sarmal", "Kalıtım", "Hücre", "Kromozom"] },
    { word: "Atom", taboo: ["Parçacık", "Çekirdek", "Proton", "Nötron", "Elektron"] },
    { word: "Evrim", taboo: ["Darwin", "Tür", "Değişim", "Doğal Seçilim", "Maymun"] },
    { word: "Fizik", taboo: ["Newton", "Einstein", "Kuvvet", "Enerji", "Madde"] },
    { word: "Kimya", taboo: ["Element", "Molekül", "Reaksiyon", "Laboratuvar", "Deney"] },
    { word: "Biyoloji", taboo: ["Canlı", "Hücre", "Yaşam", "Genetik", "Botanik"] },
    { word: "Astronomi", taboo: ["Uzay", "Yıldız", "Gezegen", "Teleskop", "Galaksi"] },
    { word: "Deney", taboo: ["Laboratuvar", "Bilim", "Tüp", "Hipotez", "Sonuç"] },
    { word: "Hipotez", taboo: ["Teori", "Tahmin", "Varsayım", "Bilimsel", "Test"] },
    { word: "Teori", taboo: ["Kuram", "Bilim", "Einstein", "İzafiyet", "Kanıt"] },
    { word: "Mikroskop", taboo: ["Küçük", "Büyütmek", "Hücre", "Bakteri", "Laboratuvar"] },
    { word: "Teleskop", taboo: ["Uzay", "Bakmak", "Yıldız", "Gözlem", "Hubble"] },
    { word: "Gezegen", taboo: ["Güneş", "Sistem", "Yörünge", "Mars", "Jüpiter"] },
    { word: "Galaksi", taboo: ["Samanyolu", "Yıldız", "Uzay", "Andromeda", "Sarmal"] },
    { word: "Işık Hızı", taboo: ["Einstein", "Boşluk", "Sürat", "Fizik", "Görelilik"] },
    { word: "Kara Delik", taboo: ["Uzay", "Çekim", "Yıldız", "Işık", "Stephen Hawking"] },
    { word: "Kuantum", taboo: ["Fizik", "Parçacık", "Belirsizlik", "Planck", "Mekanik"] },
    { word: "Fosil", taboo: ["Eski", "Kalıntı", "Dinozor", "Arkeoloji", "Toprak"] },
    { word: "Aşı", taboo: ["Hastalık", "Bağışıklık", "Virüs", "Korunma", "İğne"] },
    { word: "Antibiyotik", taboo: ["Bakteri", "İlaç", "Enfeksiyon", "Tedavi", "Penisilin"] },
    { word: "Periyodik Tablo", taboo: ["Element", "Kimya", "Mendeleyev", "Grup", "Atom Numarası"] },
    { word: "Yer Çekimi", taboo: ["Newton", "Elma", "Kuvvet", "Düşmek", "Kütle"] },
    { word: "Bilim İnsanı", taboo: ["Araştırma", "Deney", "Nobel", "Akademisyen", "Makale"] },
    { word: "Keşif", taboo: ["Yeni", "Bulmak", "Amerika", "Coğrafi", "İcat"] },
    { word: "İcat", taboo: ["Buluş", "Yeni", "Edison", "Ampul", "Mucit"] },
  ],
  sanat: [
    { word: "Tablo", taboo: ["Resim", "Yağlıboya", "Tuval", "Fırça", "Mona Lisa"] },
    { word: "Heykel", taboo: ["Yontmak", "Mermer", "Bronz", "Rodin", "Üç Boyutlu"] },
    { word: "Mona Lisa", taboo: ["Tablo", "Leonardo da Vinci", "Louvre", "Gülümseme", "Resim"] },
    { word: "Ressam", taboo: ["Fırça", "Tuval", "Boya", "Tablo", "Picasso"] },
    { word: "Müze", taboo: ["Sergi", "Eser", "Sanat", "Galeri", "Tarihi"] },
    { word: "Seramik", taboo: ["Çamur", "Toprak", "Vazo", "Fırın", "Çömlek"] },
    { word: "Mozaik", taboo: ["Taş", "Parça", "Desen", "Zemin", "Antik"] },
    { word: "Opera", taboo: ["Sahne", "Şarkı", "Müzik", "Arya", "Tiyatro"] },
    { word: "Bale", taboo: ["Dans", "Tütü", "Kuğu Gölü", "Zarafet", "Puant"] },
    { word: "Tiyatro", taboo: ["Sahne", "Oyuncu", "Perde", "Oyun", "Dekor"] },
    { word: "Fırça", taboo: ["Resim", "Boya", "Tuval", "Sürmek", "Ressam"] },
    { word: "Tuval", taboo: ["Resim", "Şövale", "Bez", "Ressam", "Boya"] },
    { word: "Palet", taboo: ["Boya", "Renk", "Karıştırmak", "Ressam", "Fırça"] },
    { word: "Portre", taboo: ["Resim", "Yüz", "İnsan", "Çizmek", "Kişi"] },
    { word: "Manzara", taboo: ["Resim", "Doğa", "Dağ", "Deniz", "Görünüm"] },
    { word: "Soyut Sanat", taboo: ["Figürsüz", "Modern", "Renk", "Şekil", "Kandinsky"] },
    { word: "Pop Art", taboo: ["Andy Warhol", "Popüler", "Kültür", "Campbell's", "Renkli"] },
    { word: "Sürrealizm", taboo: ["Gerçeküstücülük", "Salvador Dali", "Rüya", "Bilinçaltı", "Hayal"] },
    { word: "Empresyonizm", taboo: ["İzlenimcilik", "Monet", "Işık", "Renk", "Doğa"] },
    { word: "Kübİzm", taboo: ["Picasso", "Geometrik", "Şekil", "Nesne", "Perspektif"] },
    { word: "Galeri", taboo: ["Sanat", "Sergi", "Tablo", "Müze", "Eser"] },
    { word: "Sergi", taboo: ["Müze", "Galeri", "Sanat", "Eser", "Açılış"] },
    { word: "Eleştirmen", taboo: ["Yorum", "Değerlendirme", "Sanat", "Yazı", "Makale"] },
    { word: "İlham", taboo: ["Esin", "Yaratıcılık", "Fikir", "Sanatçı", "Peri"] },
    { word: "Estetik", taboo: ["Güzellik", "Sanat", "Uyum", "Görsel", "Beğeni"] },
  ],
  müzik: [
    { word: "Nota", taboo: ["Müzik", "Porte", "Do Re Mi", "Sol Anahtarı", "Ses"] },
    { word: "Gitar", taboo: ["Tel", "Pena", "Akustik", "Elektro", "Rock"] },
    { word: "Piyano", taboo: ["Tuş", "Siyah Beyaz", "Klasik", "Kuyruklu", "Çalmak"] },
    { word: "Keman", taboo: ["Yay", "Tel", "Klasik", "Orkestra", "Viyola"] },
    { word: "Bateri", taboo: ["Davul", "Zil", "Baget", "Ritim", "Çalmak"] },
    { word: "Orkestra", taboo: ["Şef", "Senfoni", "Keman", "Enstrüman", "Klasik"] },
    { word: "Konser", taboo: ["Canlı", "Sahne", "Bilet", "Seyirci", "Şarkıcı"] },
    { word: "Albüm", taboo: ["Şarkı", "Kayıt", "CD", "Plak", "Sanatçı"] },
    { word: "Rock", taboo: ["Gitar", "Bateri", "Sert", "Metal", "Queen"] },
    { word: "Pop", taboo: ["Michael Jackson", "Madonna", "Liste", "Hit", "Dans"] },
    { word: "Caz", taboo: ["Saksafon", "Trompet", "Doğaçlama", "Blues", "Swing"] },
    { word: "Klasik Müzik", taboo: ["Beethoven", "Mozart", "Senfoni", "Orkestra", "Piyano"] },
    { word: "Beste", taboo: ["Müzik", "Yazmak", "Nota", "Eser", "Besteci"] },
    { word: "Şarkı Sözü", taboo: ["Yazmak", "Şiir", "Nakarat", "Anlam", "Müzik"] },
    { word: "Nakarat", taboo: ["Tekrar", "Şarkı", "Koro", "Söz", "Melodi"] },
    { word: "Melodi", taboo: ["Ezgi", "Nota", "Şarkı", "Ritim", "Kulağa Hoş Gelen"] },
    { word: "Ritim", taboo: ["Tempo", "Vuruş", "Davul", "Dans", "Müzik"] },
    { word: "Enstrüman", taboo: ["Alet", "Çalmak", "Müzik", "Gitar", "Piyano"] },
    { word: "Vokal", taboo: ["Ses", "Şarkıcı", "Söylemek", "Solist", "Mikrofon"] },
    { word: "Koro", taboo: ["Topluluk", "Şarkı Söylemek", "Ses", "Şef", "Kilise"] },
    { word: "DJ", taboo: ["Müzik", "Çalmak", "Parti", "Kulüp", "Set"] },
    { word: "Plak", taboo: ["Pikap", "Eski", "Vinil", "İğne", "Albüm"] },
    { word: "Kulaklık", taboo: ["Müzik", "Dinlemek", "Ses", "Kablo", "Cihaz"] },
    { word: "Festival", taboo: ["Müzik", "Konser", "Açık Hava", "Bilet", "Yaz"] },
    { word: "Saksafon", taboo: ["Caz", "Üflemeli", "Enstrüman", "Metal", "Ses"] },
  ],
  edebiyat: [
    { word: "Roman", taboo: ["Kitap", "Hikaye", "Karakter", "Yazar", "Kurgu"] },
    { word: "Şiir", taboo: ["Dize", "Mısra", "Kafiye", "Şair", "Uyak"] },
    { word: "Yazar", taboo: ["Kitap", "Kalem", "Roman", "Eser", "İmza"] },
    { word: "Kütüphane", taboo: ["Kitap", "Okumak", "Sessizlik", "Raf", "Ödünç"] },
    { word: "Don Kişot", taboo: ["Roman", "Cervantes", "Yel Değirmeni", "Sancho Panza", "İspanya"] },
    { word: "Hamlet", taboo: ["Shakespeare", "Tiyatro", "Danimarka", "Olmak ya da olmamak", "Trajedi"] },
    { word: "Suç ve Ceza", taboo: ["Dostoyevski", "Roman", "Raskolnikov", "Vicdan", "Rus"] },
    { word: "İnce Memed", taboo: ["Yaşar Kemal", "Roman", "Ağa", "Eşkıya", "Çukurova"] },
    { word: "Masal", taboo: ["Çocuk", "Hikaye", "Peri", "Mutlu Son", "Evvel zaman içinde"] },
    { word: "Hikaye", taboo: ["Öykü", "Kısa", "Anlatı", "Olay", "Karakter"] },
    { word: "Karakter", taboo: ["Roman", "Hikaye", "Kişi", "Canlandırmak", "Başrol"] },
    { word: "Kafiye", taboo: ["Uyak", "Şiir", "Dize", "Ses", "Benzerlik"] },
    { word: "Dize", taboo: ["Mısra", "Şiir", "Satır", "Kafiye", "Şair"] },
    { word: "Beyit", taboo: ["Divan", "Edebiyat", "İki", "Dize", "Şiir"] },
    { word: "Epik", taboo: ["Destan", "Kahramanlık", "Savaş", "Homeros", "Şiir"] },
    { word: "Lirik", taboo: ["Duygu", "Şiir", "Aşk", "Coşku", "His"] },
    { word: "Trajedi", taboo: ["Tiyatro", "Acı", "Son", "Keder", "Shakespeare"] },
    { word: "Komedi", taboo: ["Tiyatro", "Gülmek", "Eğlence", "Mizah", "Mutlu Son"] },
    { word: "Biyografi", taboo: ["Hayat", "Hikaye", "Yaşam Öyküsü", "Yazar", "Anı"] },
    { word: "Otobiyografi", taboo: ["Kendi", "Hayatı", "Yazmak", "Anı", "Yaşam"] },
    { word: "Deneme", taboo: ["Yazı", "Fikir", "Düşünce", "Montaigne", "Makale"] },
    { word: "Nobel Ödülü", taboo: ["Edebiyat", "Orhan Pamuk", "İsveç", "Alfred", "Bilim"] },
    { word: "Çeviri", taboo: ["Dil", "Tercüme", "Kitap", "Yabancı", "Anlam"] },
    { word: "Editör", taboo: ["Yayınevi", "Düzeltmek", "Metin", "Kitap", "Yazar"] },
    { word: "Yayınevi", taboo: ["Kitap", "Basmak", "Yayınlamak", "Editör", "Matbaa"] },
  ],
  mitoloji: [
    { word: "Zeus", taboo: ["Yunan", "Tanrı", "Şimşek", "Olimpos", "Baba"] },
    { word: "Poseidon", taboo: ["Deniz", "Tanrı", "Üç Dişli Mızrak", "Yunan", "Deprem"] },
    { word: "Hades", taboo: ["Yeraltı", "Ölüler", "Tanrı", "Cehennem", "Yunan"] },
    { word: "Afrodit", taboo: ["Güzellik", "Aşk", "Tanrıça", "Venüs", "Yunan"] },
    { word: "Thor", taboo: ["Çekiç", "Şimşek", "İskandinav", "Tanrı", "Asgard"] },
    { word: "Loki", taboo: ["Hile", "Kötülük", "İskandinav", "Tanrı", "Kardeş"] },
    { word: "Odin", taboo: ["İskandinav", "Tanrıların Babası", "Asgard", "Tek Göz", "Bilgelik"] },
    { word: "Anka Kuşu", taboo: ["Simurg", "Küllerinden Doğmak", "Efsane", "Ateş", "Zümrüt"] },
    { word: "Pegasus", taboo: ["Kanatlı At", "Uçmak", "Yunan", "Beyaz", "Efsane"] },
    { word: "Medusa", taboo: ["Yılan", "Saç", "Taşa Çevirmek", "Gorgon", "Yunan"] },
    { word: "Minotaur", taboo: ["Labirent", "Boğa", "Adam", "Girit", "Yaratık"] },
    { word: "Centaur", taboo: ["At Adam", "Yarı İnsan", "Ok", "Yay", "Yunan"] },
    { word: "Siren", taboo: ["Deniz", "Şarkı", "Büyüleyici", "Kaya", "Denizci"] },
    { word: "Cerberus", taboo: ["Üç Başlı Köpek", "Hades", "Yeraltı", "Bekçi", "Yunan"] },
    { word: "Valhalla", taboo: ["Cennet", "Savaşçı", "İskandinav", "Odin", "Asgard"] },
    { word: "Olimpos", taboo: ["Dağ", "Yunan", "Tanrılar", "Ev", "Zeus"] },
    { word: "Truva Atı", taboo: ["Savaş", "Hile", "Tahta", "Odysseus", "Yunan"] },
    { word: "Aşil", taboo: ["Topuk", "Yunan", "Savaşçı", "Ölümsüz", "Zayıf Nokta"] },
    { word: "Herkül", taboo: ["Güç", "Yunan", "12 Görev", "Yarı Tanrı", "Kuvvet"] },
    { word: "Ra", taboo: ["Mısır", "Güneş", "Tanrı", "Firavun", "Piramit"] },
    { word: "Anubis", taboo: ["Mısır", "Çakal", "Ölüm", "Mumya", "Tanrı"] },
    { word: "Gılgamış", taboo: ["Destan", "Sümer", "Kral", "Ölümsüzlük", "Mezopotamya"] },
    { word: "Tepegöz", taboo: ["Dede Korkut", "Tek Göz", "Dev", "Canavar", "Oğuz"] },
    { word: "Ejderha", taboo: ["Ateş", "Kanat", "Canavar", "Efsane", "Uçmak"] },
    { word: "Peri", taboo: ["Büyü", "Kanat", "Masal", "Sihir", "Küçük"] },
  ],
  hayvanlar: [
    { word: "Aslan", taboo: ["Kral", "Orman", "Yele", "Kükremek", "Kedi"] },
    { word: "Fil", taboo: ["Hortum", "Büyük", "Fildişi", "Afrika", "Kulak"] },
    { word: "Zürafa", taboo: ["Uzun", "Boyun", "Benekli", "Afrika", "Hayvan"] },
    { word: "Penguen", taboo: ["Kutup", "Soğuk", "Uçamayan", "Kuş", "Buz"] },
    { word: "Yılan", taboo: ["Sürünmek", "Zehir", "Tıslamak", "Deri", "Kobra"] },
    { word: "Timsah", taboo: ["Sürüngen", "Su", "Gözyaşı", "Çene", "Bataklık"] },
    { word: "Maymun", taboo: ["Muz", "Ağaç", "Tırmanmak", "Şempanze", "İnsan"] },
    { word: "Ayı", taboo: ["Kış Uykusu", "Bal", "Boz", "Kutup", "Pençe"] },
    { word: "Kurt", taboo: ["Sürü", "Ulumak", "Avlanmak", "Köpek", "Vahşi"] },
    { word: "Tilki", taboo: ["Kurnaz", "Kuyruk", "Turuncu", "Kürk", "Av"] },
    { word: "Tavşan", taboo: ["Havuç", "Hızlı", "Zıplamak", "Kulak", "Yumuşak"] },
    { word: "Sincap", taboo: ["Ceviz", "Ağaç", "Fındık", "Kuyruk", "Kemirgen"] },
    { word: "Kirpi", taboo: ["Diken", "Top", "Savunma", "Yumak", "Hayvan"] },
    { word: "Kaplumbağa", taboo: ["Yavaş", "Kabuk", "Ev", "Sert", "Tosbağa"] },
    { word: "Kurbağa", taboo: ["Zıplamak", "Göl", "Vırak", "Yeşil", "Sinek"] },
    { word: "Kelebek", taboo: ["Tırtıl", "Kanat", "Uçmak", "Renkli", "Koza"] },
    { word: "Arı", taboo: ["Bal", "Sokmak", "Kovan", "Vız", "Çiçek"] },
    { word: "Karınca", taboo: ["Çalışkan", "Koloni", "Toprak", "Yuva", "Küçük"] },
    { word: "Örümcek", taboo: ["Ağ", "Sekiz Bacak", "Böcek", "Tarantula", "İp"] },
    { word: "Yunus", taboo: ["Deniz", "Akıllı", "Balık", "Gösteri", "Okyanus"] },
    { word: "Balina", taboo: ["Okyanus", "Büyük", "Mavi", "Su Püskürtmek", "Memeli"] },
    { word: "Köpekbalığı", taboo: ["Deniz", "Yırtıcı", "Jaws", "Yüzgeç", "Okyanus"] },
    { word: "Ahtapot", taboo: ["Sekiz Kol", "Deniz", "Mürekkep", "Vantuz", "Kafa"] },
    { word: "Denizanası", taboo: ["Okyanus", "Zehirli", "Dokunaç", "Şeffaf", "Yüzmek"] },
    { word: "Deve", taboo: ["Çöl", "Hörgüç", "Su", "Sıcak", "Kum"] },
  ],
  bitkiler: [
    { word: "Gül", taboo: ["Çiçek", "Diken", "Kırmızı", "Koku", "Aşk"] },
    { word: "Papatya", taboo: ["Çiçek", "Beyaz", "Sarı", "Fal", "Yaprak"] },
    { word: "Lale", taboo: ["Çiçek", "Soğan", "Hollanda", "Osmanlı", "İstanbul"] },
    { word: "Kaktüs", taboo: ["Diken", "Çöl", "Su", "Yeşil", "Bitki"] },
    { word: "Çam Ağacı", taboo: ["Kozalak", "İğne", "Yeşil", "Noel", "Orman"] },
    { word: "Meşe", taboo: ["Ağaç", "Palamut", "Sert", "Odun", "Yaprak"] },
    { word: "Zeytin Ağacı", taboo: ["Meyve", "Yağ", "Akdeniz", "Yeşil", "Siyah"] },
    { word: "Ayçiçeği", taboo: ["Sarı", "Güneş", "Tarlası", "Çekirdek", "Yağ"] },
    { word: "Mantar", taboo: ["Zehirli", "Yemek", "Şapka", "Orman", "Spor"] },
    { word: "Yosun", taboo: ["Deniz", "Yeşil", "Su", "Kaya", "Bitki"] },
    { word: "Sarmaşık", taboo: ["Tırmanmak", "Duvar", "Yeşil", "Bitki", "Yaprak"] },
    { word: "Bambu", taboo: ["Uzak Doğu", "Panda", "Yeşil", "Uzun", "Sert"] },
    { word: "Buğday", taboo: ["Tarla", "Ekmek", "Un", "Başak", "Sarı"] },
    { word: "Mısır", taboo: ["Koçan", "Sarı", "Patlamış", "Tane", "Tarla"] },
    { word: "Pirinç", taboo: ["Pilav", "Çeltik", "Asya", "Su", "Tane"] },
    { word: "Patates", taboo: ["Toprak", "Yumru", "Kızartma", "Cips", "Yemek"] },
    { word: "Domates", taboo: ["Kırmızı", "Salça", "Sebze", "Salata", "Yemek"] },
    { word: "Soğan", taboo: ["Acı", "Göz Yaşı", "Yemek", "Doğramak", "Beyaz"] },
    { word: "Sarımsak", taboo: ["Koku", "Beyaz", "Yemek", "Diş", "Antibiyotik"] },
    { word: "Nane", taboo: ["Yeşil", "Ferahlatan", "Koku", "Çay", "Sakız"] },
    { word: "Fesleğen", taboo: ["Reyhan", "Koku", "Yeşil", "Yaprak", "İtalya"] },
    { word: "Orkide", taboo: ["Çiçek", "Zarif", "Saksı", "Mor", "Beyaz"] },
    { word: "Eğrelti Otu", taboo: ["Yaprak", "Yeşil", "Orman", "Tohumsuz", "Bitki"] },
    { word: "Nilüfer", taboo: ["Göl", "Çiçek", "Su", "Yaprak", "Beyaz"] },
    { word: "Aloe Vera", taboo: ["Jel", "Cilt", "Yeşil", "Dikenli", "Bitki"] },
  ],
  meslekler: [
    { word: "Doktor", taboo: ["Hastane", "Hasta", "Tıp", "Stetoskop", "Tedavi"] },
    { word: "Öğretmen", taboo: ["Okul", "Öğrenci", "Ders", "Tahta", "Eğitim"] },
    { word: "Mühendis", taboo: ["İnşaat", "Makine", "Proje", "Hesaplama", "Bilgisayar"] },
    { word: "Avukat", taboo: ["Dava", "Mahkeme", "Hukuk", "Savunma", "Cübbe"] },
    { word: "Polis", taboo: ["Güvenlik", "Suç", "Karakol", "Üniforma", "Silah"] },
    { word: "İtfaiyeci", taboo: ["Yangın", "Söndürmek", "Hortum", "Merdiven", "Kırmızı"] },
    { word: "Aşçı", taboo: ["Yemek", "Mutfak", "Restoran", "Şef", "Kepçe"] },
    { word: "Pilot", taboo: ["Uçak", "Uçmak", "Kokpit", "Kaptan", "Havaalanı"] },
    { word: "Hemşire", taboo: ["Hastane", "Doktor", "İğne", "Hasta Bakımı", "Serum"] },
    { word: "Mimar", taboo: ["Bina", "Çizim", "Proje", "Tasarım", "Yapı"] },
    { word: "Eczacı", taboo: ["İlaç", "Reçete", "Hastane", "Nöbet", "Sağlık"] },
    { word: "Diş Hekimi", taboo: ["Ağız", "Çürük", "Dolgu", "Kanal Tedavisi", "Doktor"] },
    { word: "Veteriner", taboo: ["Hayvan", "Kedi", "Köpek", "Klinik", "Doktor"] },
    { word: "Gazeteci", taboo: ["Haber", "Muhabir", "Gazete", "Röportaj", "Makale"] },
    { word: "Yazılımcı", taboo: ["Kod", "Bilgisayar", "Program", "Uygulama", "İnternet"] },
    { word: "Çiftçi", taboo: ["Tarla", "Traktör", "Ekin", "Hasat", "Toprak"] },
    { word: "Berber", taboo: ["Saç", "Sakal", "Kesmek", "Makas", "Tıraş"] },
    { word: "Terzi", taboo: ["Kumaş", "Dikiş", "Makine", "Elbise", "İğne"] },
    { word: "Şoför", taboo: ["Araba", "Sürmek", "Direksiyon", "Taksi", "Otobüs"] },
    { word: "Garson", taboo: ["Restoran", "Sipariş", "Servis", "Müşteri", "Hesap"] },
    { word: "Postacı", taboo: ["Mektup", "Kargo", "Dağıtmak", "Adres", "Zarf"] },
    { word: "Hakim", taboo: ["Mahkeme", "Yargı", "Karar", "Cübbe", "Adalet"] },
    { word: "Savcı", taboo: ["İddianame", "Mahkeme", "Hukuk", "Suç", "Adliye"] },
    { word: "Psikolog", taboo: ["Terapi", "Ruh", "Danışan", "Seans", "Duygu"] },
    { word: "Oyuncu", taboo: ["Film", "Tiyatro", "Rol", "Sahne", "Karakter"] },
  ],
  markalar: [
    { word: "Nike", taboo: ["Ayakkabı", "Spor", "Swoosh", "Just Do It", "Adidas"] },
    { word: "Apple", taboo: ["iPhone", "Mac", "Steve Jobs", "Logo", "Teknoloji"] },
    { word: "Google", taboo: ["Arama", "Motor", "İnternet", "Chrome", "Android"] },
    { word: "Coca-Cola", taboo: ["İçecek", "Kırmızı", "Asitli", "Gazlı", "Pepsi"] },
    { word: "McDonald's", taboo: ["Hamburger", "Fast Food", "Patates", "Palyaço", "Restoran"] },
    { word: "Mercedes", taboo: ["Araba", "Alman", "Lüks", "Yıldız", "Otomobil"] },
    { word: "Toyota", taboo: ["Araba", "Japon", "Corolla", "Hibrit", "Otomobil"] },
    { word: "Samsung", taboo: ["Telefon", "Televizyon", "Kore", "Elektronik", "Galaxy"] },
    { word: "Amazon", taboo: ["Alışveriş", "Online", "Jeff Bezos", "Kargo", "Site"] },
    { word: "Facebook", taboo: ["Sosyal Medya", "Mark Zuckerberg", "Paylaşmak", "Beğen", "Meta"] },
    { word: "Microsoft", taboo: ["Windows", "Bill Gates", "Yazılım", "Office", "Bilgisayar"] },
    { word: "IKEA", taboo: ["Mobilya", "İsveç", "Ev", "Montaj", "Köfte"] },
    { word: "Starbucks", taboo: ["Kahve", "Yeşil", "Logo", "Fincan", "Zincir"] },
    { word: "Adidas", taboo: ["Ayakkabı", "Spor", "Üç Çizgi", "Nike", "Alman"] },
    { word: "Sony", taboo: ["PlayStation", "Elektronik", "Japon", "Televizyon", "Walkman"] },
    { word: "Netflix", taboo: ["Dizi", "Film", "İzlemek", "Abonelik", "Streaming"] },
    { word: "Lego", taboo: ["Oyuncak", "Blok", "Parça", "Yapmak", "Danimarka"] },
    { word: "Disney", taboo: ["Mickey Mouse", "Çizgi Film", "Park", "Prenses", "Animasyon"] },
    { word: "Pepsi", taboo: ["İçecek", "Mavi", "Kola", "Gazlı", "Asitli"] },
    { word: "Ford", taboo: ["Araba", "Otomobil", "Henry", "Mustang", "Amerikan"] },
    { word: "Ferrari", taboo: ["Araba", "Kırmızı", "Lüks", "Hızlı", "İtalyan"] },
    { word: "Gucci", taboo: ["Moda", "Çanta", "Lüks", "İtalyan", "Tasarım"] },
    { word: "Zara", taboo: ["Giyim", "Mağaza", "Moda", "İspanyol", "Kıyafet"] },
    { word: "Red Bull", taboo: ["Enerji", "İçecek", "Kanatlandırır", "Boğa", "Kafein"] },
    { word: "Intel", taboo: ["İşlemci", "Bilgisayar", "Çip", "Pentium", "Teknoloji"] },
  ],
  ünlüler: [
    { word: "Cem Yılmaz", taboo: ["Komedyen", "Stand-up", "GORA", "Film", "Mizah"] },
    { word: "Tarkan", taboo: ["Megastar", "Şarkıcı", "Pop", "Kuzu Kuzu", "Konser"] },
    { word: "Sezen Aksu", taboo: ["Minik Serçe", "Şarkıcı", "Pop", "Söz Yazarı", "Albüm"] },
    { word: "Kıvanç Tatlıtuğ", taboo: ["Oyuncu", "Yakışıklı", "Mavi", "Aşk-ı Memnu", "Dizi"] },
    { word: "Beren Saat", taboo: ["Oyuncu", "Aşk-ı Memnu", "Fatmagül", "Dizi", "Bihter"] },
    { word: "Acun Ilıcalı", taboo: ["Televizyon", "Survivor", "Yarışma", "Kanal", "Medya"] },
    { word: "Nusret", taboo: ["Et", "Tuz", "Salt Bae", "Restoran", "Şef"] },
    { word: "Haluk Bilginer", taboo: ["Oyuncu", "Tiyatro", "Emmy", "Şahsiyet", "Usta"] },
    { word: "Orhan Pamuk", taboo: ["Yazar", "Nobel", "Roman", "Kitap", "Masumiyet Müzesi"] },
    { word: "Aziz Sancar", taboo: ["Bilim", "Nobel", "Kimya", "DNA", "Profesör"] },
    { word: "Barış Manço", taboo: ["Şarkıcı", "Müzisyen", "Anadolu Rock", "Çocuk", "Program"] },
    { word: "Kemal Sunal", taboo: ["Sinema", "Komedi", "İnek Şaban", "Film", "Yeşilçam"] },
    { word: "Şener Şen", taboo: ["Sinema", "Oyuncu", "Komedi", "Yeşilçam", "Vecihi"] },
    { word: "Adile Naşit", taboo: ["Sinema", "Anne", "Yeşilçam", "Hababam Sınıfı", "Kuzucuklarım"] },
    { word: "Müslüm Gürses", taboo: ["Arabesk", "Şarkıcı", "Baba", "Film", "Konser"] },
    { word: "Albert Einstein", taboo: ["Bilim", "İzafiyet", "Fizikçi", "Alman", "E=mc²"] },
    { word: "Leonardo da Vinci", taboo: ["Ressam", "Mona Lisa", "Mucit", "İtalya", "Rönesans"] },
    { word: "Michael Jackson", taboo: ["Pop", "Kral", "Dans", "Moonwalk", "Şarkıcı"] },
    { word: "Madonna", taboo: ["Pop", "Kraliçe", "Şarkıcı", "Like a Virgin", "Konser"] },
    { word: "Cristiano Ronaldo", taboo: ["Futbol", "Portekiz", "Gol", "Real Madrid", "Messi"] },
    { word: "Lionel Messi", taboo: ["Futbol", "Arjantin", "Gol", "Barcelona", "Ronaldo"] },
    { word: "Elon Musk", taboo: ["Tesla", "SpaceX", "Twitter", "Girişimci", "Zengin"] },
    { word: "Steve Jobs", taboo: ["Apple", "iPhone", "Kurucu", "Teknoloji", "Vizyoner"] },
    { word: "Oprah Winfrey", taboo: ["Talk Show", "Sunucu", "Medya", "Zengin", "Kadın"] },
    { word: "Beyoncé", taboo: ["Şarkıcı", "Diva", "Konser", "Albüm", "Single Ladies"] },
  ],
  atasözleri: [
    { word: "Damlaya damlaya göl olur", taboo: ["Birikim", "Az", "Çok", "Para", "Sabır"] },
    { word: "Sakla samanı gelir zamanı", taboo: ["İhtiyaç", "Gerekmek", "Kenara Koymak", "İleride", "Lazım"] },
    { word: "Ayağını yorganına göre uzat", taboo: ["Harcama", "Gelir", "Gider", "Denge", "Bütçe"] },
    { word: "Gülü seven dikenine katlanır", taboo: ["Zorluk", "Sevgi", "Katlanmak", "İyi", "Kötü"] },
    { word: "Ağaç yaşken eğilir", taboo: ["Çocuk", "Eğitim", "Küçük", "Alışkanlık", "Terbiye"] },
    { word: "Bugünün işini yarına bırakma", taboo: ["Ertelemek", "Tembellik", "Hemen", "Yapmak", "Görev"] },
    { word: "Acele işe şeytan karışır", taboo: ["Hızlı", "Hata", "Yavaş", "Dikkat", "Sabır"] },
    { word: "Tatlı dil yılanı deliğinden çıkarır", taboo: ["Güzel", "Söz", "İkna", "Konuşma", "Gönül"] },
    { word: "Bir elin nesi var, iki elin sesi var", taboo: ["Birlik", "Yardımlaşma", "Beraber", "Güç", "İşbirliği"] },
    { word: "Ne ekersen onu biçersin", taboo: ["Karşılık", "Sonuç", "Yapmak", "Davranış", "Etki"] },
    { word: "Ak akçe kara gün içindir", taboo: ["Para", "Birikim", "Zor", "Zaman", "Kenara Koymak"] },
    { word: "Besle kargayı oysun gözünü", taboo: ["Nankörlük", "İyilik", "Kötülük", "Vefasız", "Hayvan"] },
    { word: "Evdeki hesap çarşıya uymaz", taboo: ["Plan", "Gerçek", "Farklı", "Beklenmedik", "Durum"] },
    { word: "Hamama giren terler", taboo: ["Zorluk", "İş", "Katlanmak", "Sonuç", "Bedel"] },
    { word: "Her horoz kendi çöplüğünde öter", taboo: ["Güç", "Alan", "Kendi", "Yer", "Etkili"] },
    { word: "İşleyen demir pas tutmaz", taboo: ["Çalışmak", "Tembellik", "Aktif", "Sağlık", "Hareket"] },
    { word: "Komşu komşunun külüne muhtaçtır", taboo: ["Yardımlaşma", "Yakın", "İlişki", "İhtiyaç", "Dayanışma"] },
    { word: "Lafla peynir gemisi yürümez", taboo: ["Söz", "Eylem", "İcraat", "Boş", "Konuşmak"] },
    { word: "Öfkeyle kalkan zararla oturur", taboo: ["Sinir", "Sakin", "Hata", "Pişmanlık", "Zarar"] },
    { word: "Üzüm üzüme baka baka kararır", taboo: ["Etkilenmek", "Arkadaş", "Çevre", "Benzemek", "Birlikte"] },
    { word: "Yalancının mumu yatsıya kadar yanar", taboo: ["Doğru", "Söylemek", "Gerçek", "Ortaya Çıkmak", "Kısa"] },
    { word: "Yuvarlanan taş yosun tutmaz", taboo: ["Değişim", "Yer", "Sabit", "Çalışkan", "Tembel"] },
    { word: "Zahmetsiz rahmet olmaz", taboo: ["Çaba", "Emek", "Zorluk", "Sonuç", "Başarı"] },
    { word: "Armut dibine düşer", taboo: ["Çocuk", "Aile", "Anne", "Baba", "Benzemek"] },
    { word: "Aç ayı oynamaz", taboo: ["Karın", "Yemek", "İstek", "Güç", "Enerji"] },
  ],
  "bilgisayar-oyunları": [
    { word: "Counter-Strike", taboo: ["Terörist", "Bomba", "Silah", "FPS", "Harita"] },
    { word: "League of Legends", taboo: ["MOBA", "Riot", "Şampiyon", "Koridor", "Sihirdar Vadisi"] },
    { word: "Minecraft", taboo: ["Blok", "Kazma", "Creeper", "Hayatta Kalma", "İnşa Etmek"] },
    { word: "Fortnite", taboo: ["Battle Royale", "İnşa", "Dans", "V-Bucks", "Epic Games"] },
    { word: "GTA", taboo: ["Araba", "Hırsızlık", "Açık Dünya", "Rockstar", "Görev"] },
    { word: "The Witcher", taboo: ["Geralt", "Canavar", "Büyü", "Rivia", "CD Projekt Red"] },
    { word: "Skyrim", taboo: ["Ejderha", "Dovahkiin", "RPG", "Açık Dünya", "Bethesda"] },
    { word: "FIFA", taboo: ["Futbol", "EA Sports", "Maç", "Gol", "Ultimate Team"] },
    { word: "Call of Duty", taboo: ["Savaş", "Asker", "FPS", "Multiplayer", "Activision"] },
    { word: "Among Us", taboo: ["Impostor", "Sahtekar", "Görev", "Uzay Gemisi", "Oylama"] },
    { word: "Pac-Man", taboo: ["Sarı", "Hayalet", "Nokta", "Labirent", "Atari"] },
    { word: "Super Mario", taboo: ["Tesisatçı", "Mantar", "Prenses", "Nintendo", "Zıplamak"] },
    { word: "Zelda", taboo: ["Link", "Hyrule", "Nintendo", "Macera", "Prenses"] },
    { word: "World of Warcraft", taboo: ["MMORPG", "Blizzard", "Horde", "Alliance", "Irk"] },
    { word: "PUBG", taboo: ["Battle Royale", "Çember", "Tava", "Airdrop", "Erangel"] },
    { word: "Valorant", taboo: ["Riot", "FPS", "Ajan", "Spike", "Taktiksel"] },
    { word: "Red Dead Redemption", taboo: ["Vahşi Batı", "Kovboy", "At", "Rockstar", "Arthur Morgan"] },
    { word: "Cyberpunk 2077", taboo: ["Gelecek", "Night City", "CD Projekt Red", "RPG", "Keanu Reeves"] },
    { word: "Sims", taboo: ["Hayat", "Simülasyon", "Ev", "İnsan", "EA"] },
    { word: "Final Fantasy", taboo: ["RPG", "Japon", "Square Enix", "Sıra Tabanlı", "Kristal"] },
    { word: "Street Fighter", taboo: ["Dövüş", "Hadouken", "Ryu", "Ken", "Capcom"] },
    { word: "Mortal Kombat", taboo: ["Dövüş", "Fatality", "Scorpion", "Sub-Zero", "Turnuva"] },
    { word: "God of War", taboo: ["Kratos", "Yunan", "Mitoloji", "Tanrı", "PlayStation"] },
    { word: "Half-Life", taboo: ["Gordon Freeman", "Levye", "Valve", "FPS", "Black Mesa"] },
    { word: "Portal", taboo: ["Bulmaca", "Silah", "Aperture Science", "GLaDOS", "Valve"] },
  ],
  doğa: [
    { word: "Şelale", taboo: ["Su", "Düşmek", "Akarsu", "Yüksek", "Gürültü"] },
    { word: "Gökkuşağı", taboo: ["Renk", "Yağmur", "Güneş", "Kemer", "Yedi"] },
    { word: "Fırtına", taboo: ["Rüzgar", "Yağmur", "Şimşek", "Gök Gürültüsü", "Hava"] },
    { word: "Hortum", taboo: ["Rüzgar", "Dönmek", "Siklon", "Tornado", "Yıkıcı"] },
    { word: "Buzul", taboo: ["Buz", "Soğuk", "Kutup", "Erimek", "Dağ"] },
    { word: "Mağara", taboo: ["Karanlık", "Yeraltı", "Sarkıt", "Dikit", "Yarasa"] },
    { word: "Kanyon", taboo: ["Vadi", "Derin", "Nehir", "Aşınma", "Kaya"] },
    { word: "Mercan Resifi", taboo: ["Deniz", "Balık", "Renkli", "Okyanus", "Dalmak"] },
    { word: "Gelgit", taboo: ["Deniz", "Ay", "Yükselmek", "Alçalmak", "Su Seviyesi"] },
    { word: "Kumul", taboo: ["Çöl", "Kum", "Tepe", "Rüzgar", "Sarı"] },
    { word: "Ekosistem", taboo: ["Canlı", "Çevre", "Denge", "Doğa", "Biyotik"] },
    { word: "Habitat", taboo: ["Yaşam Alanı", "Canlı", "Doğal", "Ortam", "Ev"] },
    { word: "Erozyon", taboo: ["Toprak", "Aşınma", "Rüzgar", "Su", "Kaybetmek"] },
    { word: "Fotosentez", taboo: ["Bitki", "Güneş", "Oksijen", "Klorofil", "Işık"] },
    { word: "Tozlaşma", taboo: ["Çiçek", "Arı", "Polen", "Bitki", "Üreme"] },
    { word: "Mevsim", taboo: ["Yaz", "Kış", "İlkbahar", "Sonbahar", "Yıl"] },
    { word: "Gündönümü", taboo: ["Yaz", "Kış", "En Uzun", "En Kısa", "Gün"] },
    { word: "Ekinoks", taboo: ["Gece", "Gündüz", "Eşit", "İlkbahar", "Sonbahar"] },
    { word: "Atmosfer", taboo: ["Hava", "Gaz", "Dünya", "Ozon", "Katman"] },
    { word: "Biyom", taboo: ["İklim", "Bitki Örtüsü", "Çöl", "Tundra", "Ekosistem"] },
    { word: "Tundra", taboo: ["Soğuk", "Kutup", "Buzlu", "Bitki Örtüsü", "Biyom"] },
    { word: "Savana", taboo: ["Afrika", "Çayır", "Aslan", "Sıcak", "Ot"] },
    { word: "Delta", taboo: ["Nehir", "Deniz", "Ova", "Alüvyon", "Ağız"] },
    { word: "Falez", taboo: ["Yalıyar", "Uçurum", "Deniz", "Kıyı", "Dalga"] },
    { word: "Krater", taboo: ["Göl", "Volkan", "Çukur", "Patlama", "Ay"] },
  ],
  uzay: [
    { word: "Gezegen", taboo: ["Yıldız", "Yörünge", "Güneş Sistemi", "Mars", "Jüpiter"] },
    { word: "Yıldız", taboo: ["Güneş", "Parlak", "Gökyüzü", "Takım", "Işık"] },
    { word: "Galaksi", taboo: ["Samanyolu", "Andromeda", "Yıldız Kümesi", "Sarmal", "Evren"] },
    { word: "Astronot", taboo: ["Uzay", "Mekiği", "Roket", "Ay", "Gezgin"] },
    { word: "Teleskop", taboo: ["Gözlem", "Yıldız", "Bakmak", "Hubble", "Mercek"] },
    { word: "Kara Delik", taboo: ["Çekim", "Işık", "Yıldız", "Tekillik", "Hawking"] },
    { word: "Güneş Sistemi", taboo: ["Gezegen", "Yörünge", "Merkür", "Dünya", "Yıldız"] },
    { word: "Uydu", taboo: ["Ay", "Yörünge", "Gezegen", "Yapay", "İletişim"] },
    { word: "Meteor", taboo: ["Göktaşı", "Atmosfer", "Düşmek", "Kayan Yıldız", "Ateş Topu"] },
    { word: "Kuyruklu Yıldız", taboo: ["Buz", "Toz", "Güneş", "Yörünge", "Halley"] },
    { word: "Nebula", taboo: ["Bulutsu", "Gaz", "Toz", "Yıldız", "Renkli"] },
    { word: "Evren", taboo: ["Uzay", "Genişlemek", "Büyük Patlama", "Galaksi", "Sonsuz"] },
    { word: "Büyük Patlama", taboo: ["Evren", "Başlangıç", "Teori", "Genişleme", "Tekillik"] },
    { word: "Uzay Mekiği", taboo: ["Roket", "Astronot", "Fırlatma", "Atmosfer", "NASA"] },
    { word: "Roket", taboo: ["Fırlatma", "Uzay", "Mekik", "İtici Güç", "Yakıt"] },
    { word: "Mars", taboo: ["Kızıl Gezegen", "Koloni", "Su", "Robot", "Güneş Sistemi"] },
    { word: "Jüpiter", taboo: ["En Büyük", "Gezegen", "Gaz Devi", "Leke", "Güneş Sistemi"] },
    { word: "Satürn", taboo: ["Halka", "Gezegen", "Gaz Devi", "Titan", "Güneş Sistemi"] },
    { word: "Uranüs", taboo: ["Gezegen", "Mavi", "Yan Yatmış", "Buz Devi", "Güneş Sistemi"] },
    { word: "Neptün", taboo: ["Gezegen", "Mavi", "Uzak", "Buz Devi", "Güneş Sistemi"] },
    { word: "Plüton", taboo: ["Cüce Gezegen", "Uzak", "Soğuk", "Güneş Sistemi", "Yörünge"] },
    { word: "Işık Yılı", taboo: ["Mesafe", "Uzay", "Ölçü", "Hız", "Zaman"] },
    { word: "Uzaylı", taboo: ["Yaratık", "UFO", "Dünya Dışı", "Yeşil", "Gezegen"] },
    { word: "NASA", taboo: ["Uzay", "Ajans", "Amerika", "Roket", "Apollo"] },
    { word: "Yörünge", taboo: ["Gezegen", "Dönmek", "Uydu", "Elips", "Güneş"] },
  ],
  taşıtlar: [
    { word: "Bisiklet", taboo: ["Pedal", "İki Tekerlek", "Sürmek", "Zincir", "Gidon"] },
    { word: "Motosiklet", taboo: ["Motor", "İki Tekerlek", "Kask", "Hız", "Sürücü"] },
    { word: "Otomobil", taboo: ["Araba", "Dört Tekerlek", "Direksiyon", "Motor", "Yolcu"] },
    { word: "Otobüs", taboo: ["Toplu Taşıma", "Yolcu", "Durak", "Bilet", "Şoför"] },
    { word: "Kamyon", taboo: ["Yük", "Büyük", "TIR", "Nakliye", "Kasa"] },
    { word: "Tren", taboo: ["Ray", "Vagon", "Makinist", "İstasyon", "Demiryolu"] },
    { word: "Metro", taboo: ["Yeraltı", "Tren", "İstasyon", "Tünel", "Toplu Taşıma"] },
    { word: "Tramvay", taboo: ["Şehir İçi", "Ray", "Elektrik", "Vatman", "Durak"] },
    { word: "Uçak", taboo: ["Uçmak", "Kanat", "Pilot", "Havaalanı", "Yolcu"] },
    { word: "Helikopter", taboo: ["Pervane", "Uçmak", "Dikey", "İniş", "Pilot"] },
    { word: "Gemi", taboo: ["Deniz", "Yüzmek", "Liman", "Kaptan", "Vapur"] },
    { word: "Feribot", taboo: ["Araba", "Deniz", "Taşımak", "Vapur", "İskele"] },
    { word: "Yat", taboo: ["Lüks", "Deniz", "Tekne", "Marina", "Gezi"] },
    { word: "Tekne", taboo: ["Su", "Kürek", "Yelken", "Balıkçı", "Gemi"] },
    { word: "Denizaltı", taboo: ["Su Altı", "Okyanus", "Periskop", "Askeri", "Dalış"] },
    { word: "Zeplin", taboo: ["Hava Gemisi", "Balon", "Uçmak", "Hindenburg", "Helyum"] },
    { word: "Sıcak Hava Balonu", taboo: ["Uçmak", "Sepet", "Ateş", "Gökyüzü", "Kapadokya"] },
    { word: "Ambulans", taboo: ["Hasta", "Acil", "Siren", "Hastane", "Sağlık"] },
    { word: "İtfaiye Aracı", taboo: ["Yangın", "Kırmızı", "Siren", "Hortum", "Merdiven"] },
    { word: "Polis Arabası", taboo: ["Siren", "Memur", "Suç", "Takip", "Mavi"] },
    { word: "Taksi", taboo: ["Sarı", "Müşteri", "Para", "Şoför", "Durak"] },
    { word: "Traktör", taboo: ["Tarla", "Çiftçi", "Tarım", "Römork", "Tekerlek"] },
    { word: "Fayton", taboo: ["At", "Araba", "Nostaljik", "Turistik", "Ada"] },
    { word: "Skuter", taboo: ["Elektrikli", "İki Tekerlek", "Kiralama", "Şehir", "Ayakta"] },
    { word: "Uzay Mekiği", taboo: ["Roket", "NASA", "Astronot", "Fırlatma", "Atmosfer"] },
  ],
  eşyalar: [
    { word: "Masa", taboo: ["Sandalye", "Oda", "Üzerine Koymak", "Ahşap", "Bacak"] },
    { word: "Sandalye", taboo: ["Oturmak", "Masa", "Bacak", "Sırt", "Mobilya"] },
    { word: "Koltuk", taboo: ["Oturmak", "Kanepe", "Salon", "Yumuşak", "Minder"] },
    { word: "Yatak", taboo: ["Uyumak", "Oda", "Çarşaf", "Yastık", "Ranza"] },
    { word: "Dolap", taboo: ["Giysi", "Kıyafet", "Asmak", "Raf", "Kapak"] },
    { word: "Çanta", taboo: ["Taşımak", "Sırt", "Kol", "Eşya", "Okul"] },
    { word: "Cüzdan", taboo: ["Para", "Kart", "Kimlik", "Deri", "Cep"] },
    { word: "Anahtar", taboo: ["Kapı", "Açmak", "Kilitlemek", "Kilit", "Metal"] },
    { word: "Kalem", taboo: ["Yazmak", "Kağıt", "Mürekkep", "Kurşun", "Tükenmez"] },
    { word: "Defter", taboo: ["Yazmak", "Sayfa", "Kalem", "Not", "Çizgili"] },
    { word: "Makas", taboo: ["Kesmek", "Kağıt", "Kumaş", "İki", "Bıçak"] },
    { word: "Tabak", taboo: ["Yemek", "Mutfak", "Porselen", "Çukur", "Kase"] },
    { word: "Çatal", taboo: ["Yemek", "Bıçak", "Kaşık", "Batırmak", "Diş"] },
    { word: "Kaşık", taboo: ["Yemek", "Çorba", "Sıvı", "Çatal", "Kepçe"] },
    { word: "Bıçak", taboo: ["Kesmek", "Keskin", "Yemek", "Çatal", "Mutfak"] },
    { word: "Bardak", taboo: ["Su", "İçmek", "Cam", "Kupa", "Fincan"] },
    { word: "Tarak", taboo: ["Saç", "Düzeltmek", "Diş", "Fırça", "Plastik"] },
    { word: "Ayna", taboo: ["Bakmak", "Yansıma", "Görüntü", "Kendin", "Cam"] },
    { word: "Havlu", taboo: ["Kurulanmak", "Banyo", "Su", "Plaj", "Yumuşak"] },
    { word: "Sabun", taboo: ["Yıkamak", "Temizlik", "Köpük", "Banyo", "El"] },
    { word: "Lamba", taboo: ["Işık", "Aydınlatma", "Ampul", "Gece", "Abajur"] },
    { word: "Halı", taboo: ["Zemin", "Yere sermek", "Desen", "Kilim", "Yün"] },
    { word: "Perde", taboo: ["Pencere", "Güneş", "Kapatmak", "Tül", "Kumaş"] },
    { word: "Priz", taboo: ["Elektrik", "Fiş", "Duvar", "Soket", "Akım"] },
    { word: "Şemsiye", taboo: ["Yağmur", "Güneş", "Açmak", "Islanmamak", "Korunmak"] },
  ],
  "soyut-kavramlar": [
    { word: "Aşk", taboo: ["Sevgi", "Duygu", "Kalp", "İlişki", "Romantik"] },
    { word: "Mutluluk", taboo: ["Sevinç", "Gülmek", "Keyif", "Huzur", "Duygu"] },
    { word: "Hüzün", taboo: ["Üzüntü", "Ağlamak", "Keder", "Duygu", "Mutsuz"] },
    { word: "Öfke", taboo: ["Sinir", "Kızgınlık", "Bağırmak", "Duygu", "Hiddet"] },
    { word: "Korku", taboo: ["Ürkmek", "Endişe", "Tehlike", "Duygu", "Heyecan"] },
    { word: "Zaman", taboo: ["Saat", "Geçmiş", "Gelecek", "Dakika", "Süre"] },
    { word: "Adalet", taboo: ["Hukuk", "Hak", "Mahkeme", "Eşitlik", "Terazi"] },
    { word: "Özgürlük", taboo: ["Hürriyet", "Bağımsızlık", "Esaret", "Hak", "Serbest"] },
    { word: "Umut", taboo: ["Beklenti", "İstek", "Gelecek", "İyimser", "Dilek"] },
    { word: "Hayal", taboo: ["Düş", "Rüya", "İstemek", "Gerçek", "Kurmak"] },
    { word: "Bilgi", taboo: ["Öğrenmek", "Veri", "Enformasyon", "Akıl", "Kitap"] },
    { word: "Güç", taboo: ["Kuvvet", "Kudret", "Enerji", "Etki", "İktidar"] },
    { word: "Güzellik", taboo: ["Estetik", "Çekici", "Hoş", "Görünüm", "Beğeni"] },
    { word: "Barış", taboo: ["Savaş", "Huzur", "Anlaşma", "Güvercin", "Sükunet"] },
    { word: "Düşünce", taboo: ["Fikir", "Akıl", "Zihin", "Mantık", "Kafa"] },
    { word: "Rüya", taboo: ["Uyumak", "Gece", "Görmek", "Hayal", "Bilinçaltı"] },
    { word: "Vicdan", taboo: ["İç Ses", "Ahlak", "Doğru", "Yanlış", "Rahat"] },
    { word: "Şans", taboo: ["Talih", "Kader", "İyi", "Kötü", "Rastlantı"] },
    { word: "Kader", taboo: ["Alın Yazısı", "Kısmet", "Talih", "Gelecek", "İnanış"] },
    { word: "Sabır", taboo: ["Beklemek", "Dayanmak", "Acele", "Huzur", "Metanet"] },
    { word: "Yalnızlık", taboo: ["Tek Başına", "Kimsesiz", "Issız", "Duygu", "Kalabalık"] },
    { word: "Başarı", taboo: ["Kazanmak", "Hedef", "Çalışmak", "Sonuç", "Galibiyet"] },
    { word: "Risk", taboo: ["Tehlike", "Zarar", "Göze Almak", "İhtimal", "Kumar"] },
    { word: "Fikir", taboo: ["Düşünce", "Görüş", "Akıl", "Öneri", "Zihin"] },
    { word: "Anı", taboo: ["Hatıra", "Geçmiş", "Unutmamak", "Yaşanmış", "Hafıza"] },
  ],
  fiiller: [
    { word: "Koşmak", taboo: ["Hızlı", "Gitmek", "Adım", "Yarış", "Spor"] },
    { word: "Yürümek", taboo: ["Adım", "Gitmek", "Yavaş", "Ayak", "Yol"] },
    { word: "Uçmak", taboo: ["Hava", "Kanat", "Kuş", "Uçak", "Gökyüzü"] },
    { word: "Yüzmek", taboo: ["Su", "Deniz", "Havuz", "Kulaç", "Balık"] },
    { word: "Yemek", taboo: ["Ağız", "Gıda", "Acıkmak", "Doymak", "Mide"] },
    { word: "İçmek", taboo: ["Sıvı", "Su", "Bardak", "Susama", "Ağız"] },
    { word: "Uyumak", taboo: ["Gece", "Yatak", "Rüya", "Göz", "Dinlenmek"] },
    { word: "Okumak", taboo: ["Kitap", "Yazı", "Göz", "Harf", "Anlamak"] },
    { word: "Yazmak", taboo: ["Kalem", "Kağıt", "Harf", "Not", "El"] },
    { word: "Konuşmak", taboo: ["Söylemek", "Dil", "Ağız", "Sohbet", "Ses"] },
    { word: "Dinlemek", taboo: ["Kulak", "Ses", "Müzik", "Anlamak", "Duymak"] },
    { word: "Görmek", taboo: ["Bakmak", "Göz", "İzlemek", "Görüntü", "Manzara"] },
    { word: "Gülmek", taboo: ["Kahkaha", "Mutlu", "Komik", "Tebessüm", "Ağız"] },
    { word: "Ağlamak", taboo: ["Gözyaşı", "Üzgün", "Hüzün", "Soğan", "Duygu"] },
    { word: "Düşünmek", taboo: ["Akıl", "Fikir", "Kafa", "Zihin", "Mantık"] },
    { word: "Sevmek", taboo: ["Aşk", "Kalp", "Duygu", "Hoşlanmak", "Beğenmek"] },
    { word: "Oynamak", taboo: ["Eğlence", "Çocuk", "Top", "Oyun", "Dans"] },
    { word: "Çalışmak", taboo: ["İş", "Mesai", "Para", "Ofis", "Emek"] },
    { word: "Öğrenmek", taboo: ["Bilgi", "Okul", "Ders", "Ezberlemek", "Yeni"] },
    { word: "Gitmek", taboo: ["Varmak", "Yol", "Uzaklaşmak", "Ayrılmak", "Gelmek"] },
    { word: "Gelmek", taboo: ["Varmak", "Yaklaşmak", "Ulaşmak", "Gitmek", "Buraya"] },
    { word: "Almak", taboo: ["Satın", "Para", "Vermek", "Sahip", "Elde"] },
    { word: "Vermek", taboo: ["Almak", "Hediye", "Sunmak", "Bağış", "El"] },
    { word: "Açmak", taboo: ["Kapı", "Pencere", "Kapatmak", "Kilit", "Anahtar"] },
    { word: "Kapatmak", taboo: ["Kapı", "Pencere", "Açmak", "Örtmek", "Kilit"] },
  ],
  cinsellik: [
    { word: "Öpüşmek", taboo: ["Dudak", "Ağız", "Fransız", "Buse", "Temas"] },
    { word: "Prezervatif", taboo: ["Kondom", "Korunma", "İlişki", "Lastik", "Kılıf"] },
    { word: "Libido", taboo: ["Cinsel", "İstek", "Arzu", "Dürtü", "Şehvet"] },
    { word: "Flört", taboo: ["Çıkmak", "Sevgili", "Buluşma", "Kur yapmak", "Yazışmak"] },
    { word: "Evlilik", taboo: ["Nikah", "Yüzük", "Gelin", "Damat", "Resmi"] },
    { word: "Doğum Kontrol", taboo: ["Hamilelik", "Korunma", "Hap", "Spiral", "Gebelik"] },
    { word: "Romantizm", taboo: ["Aşk", "Duygusal", "Mum Işığı", "Sevgili", "Jest"] },
    { word: "Bekaret", taboo: ["İlk", "İlişki", "Zar", "Kızlık", "Kaybetmek"] },
    { word: "Orgazm", taboo: ["Zevk", "Doruk", "Ulaşmak", "Boşalmak", "Cinsel"] },
    { word: "Fetiş", taboo: ["Arzu", "Nesne", "Ayakkabı", "Ayak", "Takıntı"] },
    { word: "Erojen Bölge", taboo: ["Hassas", "Dokunma", "Vücut", "Uyarılma", "Zevk"] },
    { word: "Mastürbasyon", taboo: ["Kendi", "Tatmin", "El", "Zevk", "Tek"] },
    { word: "Seks Oyuncağı", taboo: ["Vibratör", "Zevk", "Pil", "Yetişkin", "Fantezi"] },
    { word: "Cinsel Yolla Bulaşan Hastalık", taboo: ["CYBH", "Korunmasız", "İlişki", "Frengi", "HIV"] },
    { word: "Doğurganlık", taboo: ["Bebek", "Hamile", "Çocuk", "Üreme", "Yumurta"] },
    { word: "Cinsel Terapi", taboo: ["Psikolog", "Sorun", "Çift", "Danışmanlık", "Tedavi"] },
    { word: "Eşcinsellik", taboo: ["Gey", "Lezbiyen", "Aynı Cins", "İlişki", "LGBT"] },
    { word: "Biseksüellik", taboo: ["Her İki Cins", "Cinsel Yönelim", "Çekim", "LGBT", "İlişki"] },
    { word: "Ön Sevişme", taboo: ["Hazırlık", "Uyarılma", "Dokunma", "Öpüşme", "Başlangıç"] },
    { word: "Vajina", taboo: ["Kadın", "Cinsel Organ", "Genital", "Doğum", "İlişki"] },
    { word: "Penis", taboo: ["Erkek", "Cinsel Organ", "Genital", "Ereksiyon", "İlişki"] },
    { word: "Ereksiyon", taboo: ["Sertleşme", "Penis", "Uyarılma", "Cinsel", "Kan"] },
    { word: "Boşalma", taboo: ["Orgazm", "Meni", "Sıvı", "Erkek", "Zevk"] },
    { word: "Afrodizyak", taboo: ["Cinsel", "İstek", "Yiyecek", "Artırmak", "Güç"] },
    { word: "Cazibe", taboo: ["Çekicilik", "Etkileyici", "Büyüleyici", "Karşı Cins", "Mıknatıs"] },
  ],
  erotik: [
    { word: "Arzu", taboo: ["İstek", "Tutku", "Cinsel", "Şehvet", "Duygu"] },
    { word: "Tutku", taboo: ["Arzu", "Aşk", "Şiddetli", "Duygu", "İhtiras"] },
    { word: "Fantezi", taboo: ["Hayal", "Düş", "Cinsel", "İstek", "Kurmak"] },
    { word: "İç Çamaşırı", taboo: ["Sütyen", "Külot", "Dantel", "Seksi", "Giyim"] },
    { word: "Masaj", taboo: ["Yağ", "Dokunmak", "Rahatlamak", "Vücut", "Ovmаk"] },
    { word: "Şehvet", taboo: ["Arzu", "Tutku", "Cinsel", "İstek", "Nefis"] },
    { word: "Baştan Çıkarmak", taboo: ["Ayartmak", "Cazibe", "Etkilemek", "Flört", "Çekmek"] },
    { word: "Çıplak", taboo: ["Giysisiz", "Vücut", "Soyunmak", "Üstsüz", "Ten"] },
    { word: "Tensel", taboo: ["Dokunma", "Ten", "Fiziksel", "Vücut", "Temas"] },
    { word: "Uyarılma", taboo: ["Tahrik", "İstek", "Cinsel", "Hazır", "Ereksiyon"] },
    { word: "Seksi", taboo: ["Çekici", "Cazibeli", "Arzu", "Görünüm", "Kıyafet"] },
    { word: "Dantel", taboo: ["İç Çamaşırı", "Kumaş", "Süslü", "Transparan", "Giyim"] },
    { word: "Jartiyer", taboo: ["Çorap", "Bacak", "İç Çamaşırı", "Seksi", "Lastik"] },
    { word: "Kelepçe", taboo: ["Bilek", "Polis", "Fantezi", "Metal", "Bağlamak"] },
    { word: "Kırbaç", taboo: ["Vurmak", "Deri", "Fantezi", "Acı", "Şaklatmak"] },
    { word: "BDSM", taboo: ["Fantezi", "Dominant", "Sadizm", "Mazoşizm", "Rol"] },
    { word: "Striptiz", taboo: ["Soyunmak", "Dans", "Direk", "Kulüp", "Para"] },
    { word: "Role-play", taboo: ["Rol Yapma", "Fantezi", "Kostüm", "Karakter", "Oyun"] },
    { word: "Göz Bağı", taboo: ["Kapatmak", "Görmemek", "Kumaş", "Fantezi", "Sürpriz"] },
    { word: "Erotik Film", taboo: ["Yetişkin", "Sinema", "Cinsellik", "Sahne", "+18"] },
    { word: "İnleme", taboo: ["Ses", "Zevk", "Ah", "Cinsel", "Nefes"] },
    { word: "Vücut Yağı", taboo: ["Masaj", "Kaygan", "Cilt", "Sürmek", "Parlak"] },
    { word: "Bacak", taboo: ["Yürümek", "Diz", "Kalça", "Vücut", "Uzun"] },
    { word: "Dudak", taboo: ["Ağız", "Öpüşmek", "Kırmızı", "Isırmak", "Yalamak"] },
    { word: "Boyun", taboo: ["Baş", "Gerdan", "Öpmek", "Isırmak", "Kolye"] },
  ],
  "+18": [
    { word: "Bira", taboo: ["Alkol", "İçki", "Arpa", "Şişe", "Köpük"] },
    { word: "Şarap", taboo: ["Alkol", "Kırmızı", "Beyaz", "Üzüm", "Kadeh"] },
    { word: "Rakı", taboo: ["Anason", "Aslan Sütü", "Meyhane", "Meze", "Beyaz"] },
    { word: "Viski", taboo: ["Alkol", "İskoç", "Buz", "Fıçı", "Malt"] },
    { word: "Kumar", taboo: ["Para", "Oyun", "Risk", "Kaybetmek", "Casino"] },
    { word: "Poker", taboo: ["Kart", "Masa", "Cips", "Blöf", "Kumar"] },
    { word: "Dövme", taboo: ["Tattoo", "Vücut", "İğne", "Mürekkep", "Kalıcı"] },
    { word: "Piercing", taboo: ["Delmek", "Vücut", "Hızma", "Küpe", "Takı"] },
    { word: "Gece Kulübü", taboo: ["Dans", "Müzik", "Eğlence", "Barmen", "DJ"] },
    { word: "Barmen", taboo: ["İçki", "Kokteyl", "Bar", "Karıştırmak", "Shaker"] },
    { word: "Votka", taboo: ["Rus", "Alkol", "İçki", "Sek", "Shot"] },
    { word: "Tekila", taboo: ["Meksika", "Limon", "Tuz", "Shot", "Alkol"] },
    { word: "Sigara", taboo: ["Tütün", "Duman", "İçmek", "Paket", "Kül"] },
    { word: "Puro", taboo: ["Küba", "Tütün", "Kalın", "Duman", "Zengin"] },
    { word: "Nargile", taboo: ["Marpuç", "Tömbeki", "Duman", "Köz", "Kafe"] },
    { word: "Casino", taboo: ["Kumarhane", "Oyun", "Las Vegas", "Rulet", "Masa"] },
    { word: "Blackjack", taboo: ["21", "Kart", "Kumar", "Kasa", "Papaz"] },
    { word: "İddaa", taboo: ["Bahis", "Maç", "Kupon", "Oran", "Futbol"] },
    { word: "Strip Poker", taboo: ["Soyunmak", "Kart", "Oyun", "Kumar", "Kıyafet"] },
    { word: "Bekarlığa Veda", taboo: ["Parti", "Evlilik", "Düğün", "Son Gece", "Eğlence"] },
    { word: "Mahmurluk", taboo: ["Akşamdan Kalma", "Alkol", "Baş Ağrısı", "İçki", "Sabah"] },
    { word: "Shot", taboo: ["Küçük", "Bardak", "İçki", "Tekila", "Hızlı"] },
    { word: "Kokteyl", taboo: ["Karışım", "İçki", "Barmen", "Shaker", "Alkol"] },
    { word: "Meyhane", taboo: ["Rakı", "Meze", "Fasıl", "Eğlence", "Çilingir"] },
    { word: "Kadeh", taboo: ["Şarap", "Bardak", "Kaldırmak", "Tokuşturmak", "İçki"] },
  ],
  yetişkin: [
    // Bu kategori +18 kategorisinden ayrıldı ve düzeltildi.
    // İstersen buraya farklı kelimeler ekleyebiliriz. Şimdilik boş bırakıyorum.
  ],
};